---
title: "Distribución de Androcymbium Europaeum"
author: "SERPAM"
date: "09/10/2023"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: yeti

---
```{r setup, include=FALSE, message=FALSE, warning=FALSE}
library('flexdashboard')
library('rgdal')
library("leaflet") 
library("sp")
library("sf")
library("raster")
library("dplyr")
library("here")
library("mapview")
library("maptools")
library("leafem")
library("DT")
library("crosstalk")
library('readxl')
library('here')


#Lo hacemos mejor con excel
here()
basedatos <- read_excel("C:/Users/Ignacio/Desktop/Máster en Conservación de la Biodivesidad/Prácticas externas/visor_androcymbium/data/basedatos_visor.xlsx")
basedatos_vars <- read_excel("C:/Users/Ignacio/Desktop/Máster en Conservación de la Biodivesidad/Prácticas externas/visor_androcymbium/data/basedatos_variables.xlsx")

basedatos_refs <- read_excel("C:/Users/Ignacio/Desktop/Máster en Conservación de la Biodivesidad/Prácticas externas/visor_androcymbium/data/basedatos_referencias.xlsx")

basedatos[93,2] <- 36.4858


#transformar a objeto espacial 
basedatos <- SpatialPointsDataFrame(basedatos[,2:3], basedatos, proj4string = CRS("+init=epsg:4326"))

basedatos<- st_as_sf(basedatos)
#Creación de la paleta y los pop ups

sd <- SharedData$new(basedatos)
```

Mapa interactivo {data-icon="ion-stats-bars"}
=====================================  

Column {data-width=400}
-------------------------------------

### Filtros

```{r filters}
  filter_checkbox(
    id = "fuente",
    label = "Fuente del registro",
    sharedData = sd,
    group = ~fuente
  )
```

### Tabla de datos

```{r datatable}
sd %>% 
  DT::datatable(
    filter = "top",  # allows filtering on each column
    extensions = c(
      "Buttons",  # add download buttons, etc
      "Scroller"  # for scrolling down the rows rather than pagination
    ),
    rownames = FALSE,  # remove rownames
    style = "bootstrap",
    class = "compact",
    width = "100%",
    options = list(
      dom = "Blrtip",  # specify content (search box, etc)
      deferRender = TRUE,
      scrollY = 300,
      scroller = TRUE,
      columnDefs = list(
        list(
          visible = FALSE,
          targets = c(1,2,3,4,7)
        )
      ), 
      buttons = list(
        I("colvis"),  # turn columns on and off
        "csv",  # download as .csv
        "excel"  # download as .xlsx
      )
    )
  )
```



Column {data-width=600}
-------------------------------------
### Mapa

```{r map}

#para poner colores distintos por fuente 
pal <- colorFactor(palette="Set 1", domain=basedatos$fuente)
#palette.pals() #para ver las paletas de colores disponibles 
pal <- palette("Set 1")

popup_basedatos <- paste0("<h3>", basedatos$fuente,"</h3>",
                          "<strong> X:</strong> ", basedatos$x, 
                          "<br><strong> Y: </strong> ", basedatos$y 
                          )

#Creación del mapa 

sd %>% 
  leaflet::leaflet() %>% 
  leaflet::addTiles()  %>% 
  leaflet::addCircleMarkers( 
                   radius = 3, 
                   stroke = FALSE, 
                   color = ~pal, #pal =palette("Set 1") y ~pal funciona bien sin leyenda
                   fillOpacity = 0.8, 
                   group = c("CSIC-RJB-MA", "herbarioValencia", "GBIF", "Anthos", "SERPAM",                               "DelHoyo&Pedrola2010"),
                   popup = popup_basedatos) %>% 
                     
  leaflet::addProviderTiles("Esri.WorldImagery",
                   group = "Satellite (ESRI)") %>% 
  leaflet::addLayersControl(position = 'bottomright',
                   baseGroups = c('Open Street Map', 'Satellite (ESRI)'), 
                   overlayGroups = c("CSIC-RJB-MA", "herbarioValencia", "GBIF", "Anthos",                         "SERPAM", "DelHoyo&Pedrola2010"),  
                   options = layersControlOptions(collapsed = TRUE)) %>% 
  addMouseCoordinates()
 

#addLegend('bottomleft', pal= pal, values=~fuente,  title = "Fuentes",  opacity = 1)

```



Tabla de variables
=============================================================================
```{r echo=FALSE}
DT::datatable(
  basedatos_vars,
  filter = "top",
  extensions = "Scroller",
  rownames = FALSE,
  style = "bootstrap",
  class = "compact",
  width = "100%",
  options = list(deferRender = TRUE, scroller = TRUE))
```

Tabla de referencias
=============================================================================
```{r echo=FALSE}
DT::datatable(
  basedatos_refs,
  filter = "top",
  extensions = "Scroller",
  rownames = FALSE,
  style = "bootstrap",
  class = "compact",
  width = "100%",
  options = list(deferRender = TRUE, scroller = TRUE))
```


Info
=============================================================================
\
This repo contains a visualization of the spatial distribution of the Androcymbium europaeum.


